// Mgmt
// Copyright (C) James Shubin and the project contributors
// Written by James Shubin <james@shubin.ca> and the project contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// Additional permission under GNU GPL version 3 section 7
//
// If you modify this program, or any covered work, by linking or combining it
// with embedded mcl code and modules (and that the embedded mcl code and
// modules which link with this program, contain a copy of their source code in
// the authoritative form) containing parts covered by the terms of any other
// license, the licensors of this program grant you additional permission to
// convey the resulting work. Furthermore, the licensors of this program grant
// the original author, James Shubin, additional permission to update this
// additional permission if he deems it necessary to achieve the goals of this
// additional permission.

package resources

import (
	"context"
	"fmt"
	"path/filepath"
	"reflect"
	"strings"
	"time"

	"github.com/purpleidea/mgmt/engine"
	"github.com/purpleidea/mgmt/engine/traits"
)

func init() {
	engine.RegisterResource(KindAcmeCertificate, func() engine.Res { return &AcmeCertificateRes{} })
}

// AcmeCertificateRes declares a shared ACME certificate identity and optionally
// materializes the current shared bundle into local files. This resource does
// not perform ACME issuance. Issuance is performed by scheduled acme:solver:*
// resources.
type AcmeCertificateRes struct {
	traits.Base
	traits.Refreshable

	init *engine.Init

	// RequestNamespace groups certificate requests that solver resources watch.
	// The certificate namespace is request_namespace/<resource name>.
	RequestNamespace string `lang:"request_namespace" yaml:"request_namespace"`

	// Namespace is a legacy exact World namespace override. New MCL should use
	// request_namespace instead.
	Namespace string `lang:"namespace" yaml:"namespace"`

	// Domains are the DNS SANs requested for this certificate.
	Domains []string `lang:"domains" yaml:"domains"`
	// KeyAlgorithm controls the private key generated by the issuer.
	KeyAlgorithm string `lang:"key_algorithm" yaml:"key_algorithm"`
	// RenewBefore is the number of seconds before NotAfter when a bundle becomes
	// due for renewal.
	RenewBefore uint64 `lang:"renew_before" yaml:"renew_before"`

	// Local materialization paths. If any one is set, all four are required.
	Key       string `lang:"key" yaml:"key"`
	Cert      string `lang:"cert" yaml:"cert"`
	Chain     string `lang:"chain" yaml:"chain"`
	Fullchain string `lang:"fullchain" yaml:"fullchain"`

	// PrivateKeyMode is a future extension point. This implementation supports only
	// plaintext because the etcd world is explicitly trusted by the deployment.
	PrivateKeyMode string `lang:"private_key_mode" yaml:"private_key_mode"`
}

// Default returns some sensible defaults for this resource.
func (obj *AcmeCertificateRes) Default() engine.Res {
	return &AcmeCertificateRes{
		KeyAlgorithm:   acmeDefaultKeyAlgorithm,
		RenewBefore:    acmeDefaultRenewBefore,
		PrivateKeyMode: acmeDefaultPrivateKeyMode,
	}
}

// Validate if the params passed in are valid data.
func (obj *AcmeCertificateRes) Validate() error {
	if obj.RequestNamespace != "" && obj.Namespace != "" {
		return fmt.Errorf("request_namespace and namespace are mutually exclusive")
	}
	if obj.namespace() == "" {
		return fmt.Errorf("namespace must not be empty")
	}
	if strings.Contains(obj.Name(), "/") {
		return fmt.Errorf("certificate name must not contain slash")
	}
	if _, err := obj.spec(); err != nil {
		return err
	}
	paths := []string{obj.Key, obj.Cert, obj.Chain, obj.Fullchain}
	any := false
	for _, p := range paths {
		if p != "" {
			any = true
		}
	}
	if any {
		for _, p := range paths {
			if p == "" {
				return fmt.Errorf("key, cert, chain, and fullchain must all be set when local materialization is requested")
			}
			if !filepath.IsAbs(p) {
				return fmt.Errorf("local materialization path %q must be absolute", p)
			}
		}
	}
	return nil
}

// Init initializes the resource.
func (obj *AcmeCertificateRes) Init(init *engine.Init) error {
	obj.init = init
	return nil
}

// Cleanup is run by the engine to clean up after the resource is done.
func (obj *AcmeCertificateRes) Cleanup() error { return nil }

// Watch is the primary listener for this resource and it outputs events.
func (obj *AcmeCertificateRes) Watch(ctx context.Context) error {
	ns := obj.namespace()
	mapKeys := []string{}
	if obj.Namespace == "" {
		mapKeys = append(mapKeys, acmeRequestIndexKey(obj.requestNamespace()))
	}
	return acmeWatchWorld(ctx, obj.init, []string{acmeSpecKey(ns), acmeCurrentKey(ns)}, mapKeys, 30*time.Second)
}

func (obj *AcmeCertificateRes) requestNamespace() string {
	return acmeRequestNamespace(obj.RequestNamespace)
}

func (obj *AcmeCertificateRes) namespace() string {
	if obj.Namespace != "" {
		return acmeLegacyCertificateNamespace(obj.Name(), obj.Namespace)
	}
	return acmeCertificateNamespace(obj.Name(), obj.requestNamespace())
}

func (obj *AcmeCertificateRes) spec() (*acmeCertSpec, error) {
	return acmeBuildSpec(obj.Domains, obj.KeyAlgorithm, obj.RenewBefore, obj.PrivateKeyMode)
}

func (obj *AcmeCertificateRes) wantsLocalMaterialization() bool {
	return obj.Key != "" || obj.Cert != "" || obj.Chain != "" || obj.Fullchain != ""
}

func (obj *AcmeCertificateRes) localMatches(bundle *acmeCertBundle) (bool, error) {
	checks := []struct {
		path string
		data []byte
	}{
		{obj.Key, []byte(bundle.PrivateKey.PEM)},
		{obj.Cert, []byte(bundle.CertPEM)},
		{obj.Chain, []byte(bundle.ChainPEM)},
		{obj.Fullchain, []byte(bundle.FullchainPEM)},
	}
	for _, check := range checks {
		equal, err := acmeFileEqual(check.path, check.data)
		if err != nil {
			return false, err
		}
		if !equal {
			return false, nil
		}
	}
	return true, nil
}

func (obj *AcmeCertificateRes) writeLocal(bundle *acmeCertBundle) error {
	if err := acmeAtomicWriteFile(obj.Key, []byte(bundle.PrivateKey.PEM), 0600); err != nil {
		return err
	}
	if err := acmeAtomicWriteFile(obj.Cert, []byte(bundle.CertPEM), 0644); err != nil {
		return err
	}
	if err := acmeAtomicWriteFile(obj.Chain, []byte(bundle.ChainPEM), 0644); err != nil {
		return err
	}
	if err := acmeAtomicWriteFile(obj.Fullchain, []byte(bundle.FullchainPEM), 0644); err != nil {
		return err
	}
	return nil
}

// CheckApply method for resource.
func (obj *AcmeCertificateRes) CheckApply(ctx context.Context, apply bool) (bool, error) {
	ns := obj.namespace()
	spec, err := obj.spec()
	if err != nil {
		return false, err
	}

	if obj.Namespace == "" {
		indexOK, err := acmeCertificateRequestIndexed(ctx, obj.init, obj.requestNamespace(), obj.Name())
		if err != nil {
			return false, err
		}
		if !indexOK {
			if !apply {
				return false, nil
			}
			if indexOK, err = acmeRegisterCertificateRequest(ctx, obj.init, obj.requestNamespace(), obj.Name()); err != nil {
				return false, err
			}
		}
		if !indexOK {
			obj.init.Logf("ACME certificate request indexed at %s", acmeRequestIndexKey(obj.requestNamespace()))
			return false, nil
		}
	}

	var existingSpec acmeCertSpec
	specExists, err := acmeWorldReadJSON(ctx, obj.init.World, acmeSpecKey(ns), &existingSpec)
	if err != nil {
		return false, err
	}
	if specExists {
		if existingSpec.SpecDigest != spec.SpecDigest {
			return false, fmt.Errorf("world spec %s exists with digest %s, but local spec digest is %s", acmeSpecKey(ns), existingSpec.SpecDigest, spec.SpecDigest)
		}
	} else {
		if !apply {
			return false, nil
		}
		if _, err := acmeWorldWriteJSON(ctx, obj.init.World, acmeSpecKey(ns), spec); err != nil {
			return false, err
		}
		obj.init.Logf("ACME certificate spec published at %s", acmeSpecKey(ns))
		return false, nil
	}

	var current acmeCertCurrent
	currentExists, err := acmeWorldReadJSON(ctx, obj.init.World, acmeCurrentKey(ns), &current)
	if err != nil {
		return false, err
	}
	if !currentExists {
		return false, nil
	}
	if current.SpecDigest != spec.SpecDigest {
		return false, nil
	}

	var bundle acmeCertBundle
	bundleExists, err := acmeWorldReadJSON(ctx, obj.init.World, acmeBundleKey(ns, current.BundleDigest), &bundle)
	if err != nil {
		return false, err
	}
	if !bundleExists {
		return false, nil
	}
	if err := acmeBundleUsable(&bundle, spec); err != nil {
		return false, nil
	}

	if !obj.wantsLocalMaterialization() {
		return true, nil
	}

	matches, err := obj.localMatches(&bundle)
	if err != nil {
		return false, err
	}
	if matches {
		return true, nil
	}
	if !apply {
		return false, nil
	}
	if err := obj.writeLocal(&bundle); err != nil {
		return false, err
	}
	obj.init.Logf("ACME certificate bundle materialized from %s", acmeBundleKey(ns, current.BundleDigest))
	return false, nil
}

// Cmp compares two resources and returns an error if they are not equivalent.
func (obj *AcmeCertificateRes) Cmp(r engine.Res) error {
	res, ok := r.(*AcmeCertificateRes)
	if !ok {
		return fmt.Errorf("not a %s", obj.Kind())
	}
	if obj.namespace() != res.namespace() {
		return fmt.Errorf("the Namespace differs")
	}
	if obj.requestNamespace() != res.requestNamespace() {
		return fmt.Errorf("the RequestNamespace differs")
	}
	if !reflect.DeepEqual(obj.Domains, res.Domains) {
		return fmt.Errorf("the Domains differs")
	}
	if obj.KeyAlgorithm != res.KeyAlgorithm {
		return fmt.Errorf("the KeyAlgorithm differs")
	}
	if obj.RenewBefore != res.RenewBefore {
		return fmt.Errorf("the RenewBefore differs")
	}
	if obj.Key != res.Key {
		return fmt.Errorf("the Key differs")
	}
	if obj.Cert != res.Cert {
		return fmt.Errorf("the Cert differs")
	}
	if obj.Chain != res.Chain {
		return fmt.Errorf("the Chain differs")
	}
	if obj.Fullchain != res.Fullchain {
		return fmt.Errorf("the Fullchain differs")
	}
	if obj.PrivateKeyMode != res.PrivateKeyMode {
		return fmt.Errorf("the PrivateKeyMode differs")
	}
	return nil
}

// AcmeCertificateUID is the UID struct for AcmeCertificateRes.
type AcmeCertificateUID struct {
	engine.BaseUID
	name string
}

// UIDs includes all params to make a unique identification of this object.
func (obj *AcmeCertificateRes) UIDs() []engine.ResUID {
	x := &AcmeCertificateUID{
		BaseUID: engine.BaseUID{Name: obj.Name(), Kind: obj.Kind()},
		name:    obj.Name(),
	}
	return []engine.ResUID{x}
}

// UnmarshalYAML is the custom unmarshal handler for this struct.
func (obj *AcmeCertificateRes) UnmarshalYAML(unmarshal func(interface{}) error) error {
	type rawRes AcmeCertificateRes
	def := obj.Default()
	res, ok := def.(*AcmeCertificateRes)
	if !ok {
		return fmt.Errorf("could not convert to AcmeCertificateRes")
	}
	raw := rawRes(*res)
	if err := unmarshal(&raw); err != nil {
		return err
	}
	*obj = AcmeCertificateRes(raw)
	return nil
}
